name: saaivenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  # Core web framework dependencies (conda when available)
  - pydantic
  - numpy
  # ML/AI dependencies from conda-forge
  - tiktoken 
  - langchain
  - openai
  # Pip-only dependencies
  - pip:
    # FastAPI and web server
    - fastapi>=0.104.1
    - uvicorn[standard]>=0.24.0
    - pydantic-settings>=2.1.0
    # Azure AI services
    - azure-ai-projects>=1.0.0
    - azure-identity>=1.15.0
    - azure-ai-agents>=1.0.0
    - azure-search-documents>=11.4.0
    - azure-data-tables>=12.4.0
    - azure-storage-blob>=12.19.0
    # Text processing
    - semantic-text-splitter>=0.8.0
    - tokenizers>=0.15.0
    # Development dependencies
    - pytest>=7.4.0
    - pytest-asyncio>=0.21.0
    - httpx>=0.25.0
    - black>=23.10.0
    - isort>=5.12.0
    - flake8>=6.1.0
  